name: Build

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3
      - name: ユニットテスト
        run: cargo test
      - name: リリースビルド
        run: cargo build --release --bin f5rail
      - name: 外部変形生成
        run: cargo run --bin make
      - name: 保存
        uses: actions/upload-artifact@v3
        with:
          path: 外部変形/f5rail-*.zip
